{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex.fullname" . }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
data:
  es_uri: "https://{{ include "elasticsearch.masterService" .Subcharts.elasticsearch }}:{{ .Values.elasticsearch.httpPort }}"
  es_hostname: {{ include "elasticsearch.masterService" .Subcharts.elasticsearch }}
  application.conf: |
    ## ElasticSearch
    search {
      index = cortex
      uri = "https://{{ include "elasticsearch.masterService" .Subcharts.elasticsearch }}:{{ .Values.elasticsearch.httpPort }}"

      ## Advanced configuration
      # Scroll keepalive.
      #keepalive = 1m
      # Scroll page size.
      #pagesize = 50
      # Number of shards
      #nbshards = 5
      # Number of replicas
      #nbreplicas = 1
      # Arbitrary settings
      #settings {
      #  # Maximum number of nested fields
      #  mapping.nested_fields.limit = 100
      #}

      ## Authentication configuration
      username = "elastic"
      password = "123456"

      ## SSL configuration
      #keyStore {
      #  path = "/path/to/keystore"
      #  type = "JKS" # or PKCS12
      #  password = "keystore-password"
      #}
      #trustStore {
      #  path = "/path/to/trustStore"
      #  type = "JKS" # or PKCS12
      #  password = "trustStore-password"
      #}
    }


{{- end }}