apiVersion: v2
name: cortex
description: Cortex stack for k8s
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: elasticsearch
    version: "8.5.1"
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled